### ISSUE TITLE
DGCNN Implementation

### ISSUE THREAD

**Issue by andreimano** [StefanosPert/Equivariant_Optimization_CR#1]
Hi there, thanks a lot for making the code publicly available!

Will the implementation for your VN-DGCNN variant (Fig 2 + Sec. 4.1) also be made public?

Once again, thanks a lot!

**Comment by StefanosPert** [comment]
Hi, thank you for your interest in our work.
We will upload the DGCNN variant in the following days. I apologize for the delay.

**Comment by StefanosPert** [comment]
We updated the main branch and added a VN-DGCNN implementation of our method for the point cloud classification task.
