### ISSUE TITLE
Preprint contains wrong learning rate for DG-CNN

### ISSUE THREAD

**Issue by andreimano** [StefanosPert/Equivariant_Optimization_CR#4]
Hi there,

Thanks for the paper and for making the code publicly available!

I just want to point out that the preprint (https://arxiv.org/pdf/2408.13242) reports a different learning rate for DG-CNN (Appendix A1 mentions 1e-3) but when the SGD optimizer is being used, the lr is multiplied by 100 (https://github.com/StefanosPert/Equivariant_Optimization_CR/blob/f448578ee48711f5b23d3410f582097df14eb707/PCClassification/vn-dgcnn/main_cls.py#L66), so the correct LR should be 1e-1.

**Comment by StefanosPert** [comment]
Hi,

Thank you for pointing it out, we will plan to update the arxiv preprint so we will correct that as well.
